{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "7e72a80e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/vocal-remover\n",
      "loading model... done\n",
      "loading wave source... done\n",
      "stft of wave source... done\n",
      "100%|███████████████████████████████████████████| 21/21 [00:02<00:00,  8.54it/s]\n",
      "100%|███████████████████████████████████████████| 21/21 [00:01<00:00, 15.40it/s]\n",
      "validating output directory... done\n",
      "inverse stft of instruments... done\n",
      "inverse stft of vocals... done\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "%cd vocal-remover\n",
    "!python inference.py -i ../backdown.mp3 -o ../ -t -p --gpu 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "068987ba",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ubuntu\n"
     ]
    }
   ],
   "source": [
    "%cd .."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4bd58cf9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Thu Mar 30 19:16:45 2023       \n",
      "+-----------------------------------------------------------------------------+\n",
      "| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |\n",
      "|-------------------------------+----------------------+----------------------+\n",
      "| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |\n",
      "| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |\n",
      "|                               |                      |               MIG M. |\n",
      "|===============================+======================+======================|\n",
      "|   0  NVIDIA A10          On   | 00000000:06:00.0 Off |                    0 |\n",
      "|  0%   37C    P8    21W / 150W |      0MiB / 23028MiB |      0%      Default |\n",
      "|                               |                      |                  N/A |\n",
      "+-------------------------------+----------------------+----------------------+\n",
      "                                                                               \n",
      "+-----------------------------------------------------------------------------+\n",
      "| Processes:                                                                  |\n",
      "|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |\n",
      "|        ID   ID                                                   Usage      |\n",
      "|=============================================================================|\n",
      "|  No running processes found                                                 |\n",
      "+-----------------------------------------------------------------------------+\n"
     ]
    }
   ],
   "source": [
    "!nvidia-smi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6d683143",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/home/ubuntu'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f21bdb30",
   "metadata": {},
   "outputs": [],
   "source": [
    "#@title Setup 1 (just run this once)\n",
    "import os\n",
    "import glob"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5bfa4e10",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "os.chdir('so-vits-svc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e4554093",
   "metadata": {
    "jupyter": {
     "outputs_hidden": true
    },
    "scrolled": true,
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['/home/ubuntu/convert.ipynb',\n",
       " '/home/ubuntu/backdown.mp3',\n",
       " '/home/ubuntu/setup.ipynb',\n",
       " '/home/ubuntu/backdown_Vocals.wav',\n",
       " '/home/ubuntu/nmpla.mp3',\n",
       " '/home/ubuntu/backdown_Instruments.wav',\n",
       " '/home/ubuntu/pablo.mp3',\n",
       " '/home/ubuntu/so-vits-svc/requirements_win.txt',\n",
       " '/home/ubuntu/so-vits-svc/CN-README.md',\n",
       " '/home/ubuntu/so-vits-svc/models.py',\n",
       " '/home/ubuntu/so-vits-svc/sovits_utils.py',\n",
       " '/home/ubuntu/so-vits-svc/utils.py',\n",
       " '/home/ubuntu/so-vits-svc/data_utils.py',\n",
       " '/home/ubuntu/so-vits-svc/app.py',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64',\n",
       " '/home/ubuntu/so-vits-svc/flask_api.py',\n",
       " '/home/ubuntu/so-vits-svc/preprocess_hubert_f0.py',\n",
       " '/home/ubuntu/so-vits-svc/inference_gui2.py',\n",
       " '/home/ubuntu/so-vits-svc/Eng_docs.md',\n",
       " '/home/ubuntu/so-vits-svc/downloader_gui.py',\n",
       " '/home/ubuntu/so-vits-svc/train.py',\n",
       " '/home/ubuntu/so-vits-svc/resample.py',\n",
       " '/home/ubuntu/so-vits-svc/inference_main.py',\n",
       " '/home/ubuntu/so-vits-svc/spec_gen.py',\n",
       " '/home/ubuntu/so-vits-svc/onnx_export.py',\n",
       " '/home/ubuntu/so-vits-svc/preprocess_flist_config.py',\n",
       " '/home/ubuntu/so-vits-svc/README.md',\n",
       " '/home/ubuntu/so-vits-svc/requirements.txt',\n",
       " '/home/ubuntu/so-vits-svc/onnx/model_onnx_48k.py',\n",
       " '/home/ubuntu/so-vits-svc/onnx/model_onnx.py',\n",
       " '/home/ubuntu/so-vits-svc/onnx/onnx_export.py',\n",
       " '/home/ubuntu/so-vits-svc/onnx/onnx_export_48k.py',\n",
       " '/home/ubuntu/so-vits-svc/docs/2.png',\n",
       " '/home/ubuntu/so-vits-svc/docs/1.png',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/__init__.py',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/models.py',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/env.py',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/utils.py',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/nvSTFT.py',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/__pycache__/utils.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/__pycache__/env.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/vdecoder/hifigan/__pycache__/models.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/onnxexport/model_onnx.py',\n",
       " '/home/ubuntu/so-vits-svc/__pycache__/models.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/__pycache__/sovits_utils.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/hubert/hubert_model.py',\n",
       " '/home/ubuntu/so-vits-svc/hubert/__init__.py',\n",
       " '/home/ubuntu/so-vits-svc/hubert/checkpoint_best_legacy_500.pt',\n",
       " '/home/ubuntu/so-vits-svc/hubert/hubert_model_onnx.py',\n",
       " '/home/ubuntu/so-vits-svc/hubert/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/hubert/__pycache__/hubert_model.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/cluster/__init__.py',\n",
       " '/home/ubuntu/so-vits-svc/cluster/train_cluster.py',\n",
       " '/home/ubuntu/so-vits-svc/cluster/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/filelists/train.txt',\n",
       " '/home/ubuntu/so-vits-svc/filelists/test.txt',\n",
       " '/home/ubuntu/so-vits-svc/filelists/val.txt',\n",
       " '/home/ubuntu/so-vits-svc/modules/losses.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/__init__.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/commons.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/attentions.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/modules.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/mel_processing.py',\n",
       " '/home/ubuntu/so-vits-svc/modules/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/modules/__pycache__/commons.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/modules/__pycache__/modules.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/modules/__pycache__/attentions.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/configs/config.json',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/kendrick10.zip',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/docbook-xsl.css',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-test.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-reg.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megarc.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-rm.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-put.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-ls.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-dl.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-copy.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-export.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-df.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-get.html',\n",
       " '/home/ubuntu/so-vits-svc/megatools-1.11.1.20230212-linux-x86_64/docs/megatools-mkdir.html',\n",
       " '/home/ubuntu/so-vits-svc/inference/infer_tool.py',\n",
       " '/home/ubuntu/so-vits-svc/inference/chunks_temp.json',\n",
       " '/home/ubuntu/so-vits-svc/inference/__init__.py',\n",
       " '/home/ubuntu/so-vits-svc/inference/infer_tool_grad.py',\n",
       " '/home/ubuntu/so-vits-svc/inference/slicer.py',\n",
       " '/home/ubuntu/so-vits-svc/inference/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/inference/__pycache__/infer_tool.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/inference/__pycache__/slicer.cpython-38.pyc',\n",
       " '/home/ubuntu/so-vits-svc/models/ye200k/G_199200.pth',\n",
       " '/home/ubuntu/so-vits-svc/models/ye200k/config.json',\n",
       " '/home/ubuntu/so-vits-svc/models/kendrick10/kmeans_4000.pt',\n",
       " '/home/ubuntu/so-vits-svc/models/kendrick10/G_67200.pth',\n",
       " '/home/ubuntu/so-vits-svc/models/kendrick10/config.json',\n",
       " '/home/ubuntu/so-vits-svc/models/kendrick10/D_67200.pth',\n",
       " '/home/ubuntu/so-vits-svc/dataset_raw/wav_structure.txt',\n",
       " '/home/ubuntu/vocal-remover/inference.py',\n",
       " '/home/ubuntu/vocal-remover/train.py',\n",
       " '/home/ubuntu/vocal-remover/README.md',\n",
       " '/home/ubuntu/vocal-remover/requirements.txt',\n",
       " '/home/ubuntu/vocal-remover/augment.py',\n",
       " '/home/ubuntu/vocal-remover/lib/nets.py',\n",
       " '/home/ubuntu/vocal-remover/lib/__init__.py',\n",
       " '/home/ubuntu/vocal-remover/lib/utils.py',\n",
       " '/home/ubuntu/vocal-remover/lib/spec_utils.py',\n",
       " '/home/ubuntu/vocal-remover/lib/dataset.py',\n",
       " '/home/ubuntu/vocal-remover/lib/layers.py',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/spec_utils.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/__init__.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/dataset.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/utils.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/nets.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/lib/__pycache__/layers.cpython-38.pyc',\n",
       " '/home/ubuntu/vocal-remover/appendix/plot_log.py',\n",
       " '/home/ubuntu/vocal-remover/models/baseline.pth']"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "existing_files = glob.glob('/home/ubuntu/**/*.*', recursive=True)\n",
    "existing_files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "06e0a596",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: Flask in /home/ubuntu/.local/lib/python3.8/site-packages (2.2.3)\n",
      "Requirement already satisfied: importlib-metadata>=3.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask) (5.0.0)\n",
      "Requirement already satisfied: click>=8.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask) (8.1.3)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask) (2.1.2)\n",
      "Requirement already satisfied: Werkzeug>=2.2.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask) (2.2.3)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask) (3.1.2)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->Flask) (3.15.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Jinja2>=3.0->Flask) (2.1.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: Flask_Cors in /home/ubuntu/.local/lib/python3.8/site-packages (3.0.10)\n",
      "Requirement already satisfied: Six in /usr/lib/python3/dist-packages (from Flask_Cors) (1.14.0)\n",
      "Requirement already satisfied: Flask>=0.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask_Cors) (2.2.3)\n",
      "Requirement already satisfied: Werkzeug>=2.2.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask>=0.9->Flask_Cors) (2.2.3)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask>=0.9->Flask_Cors) (3.1.2)\n",
      "Requirement already satisfied: importlib-metadata>=3.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask>=0.9->Flask_Cors) (5.0.0)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask>=0.9->Flask_Cors) (2.1.2)\n",
      "Requirement already satisfied: click>=8.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Flask>=0.9->Flask_Cors) (8.1.3)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->Flask>=0.9->Flask_Cors) (3.15.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from Jinja2>=3.0->Flask>=0.9->Flask_Cors) (2.1.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: gradio in /home/ubuntu/.local/lib/python3.8/site-packages (3.23.0)\n",
      "Requirement already satisfied: matplotlib in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (3.5.3)\n",
      "Requirement already satisfied: fsspec in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (2023.3.0)\n",
      "Requirement already satisfied: pydantic in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (1.10.2)\n",
      "Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from gradio) (5.3.1)\n",
      "Requirement already satisfied: httpx in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.23.3)\n",
      "Requirement already satisfied: requests in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (2.28.1)\n",
      "Requirement already satisfied: orjson in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (3.8.9)\n",
      "Requirement already satisfied: python-multipart in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.0.6)\n",
      "Requirement already satisfied: pillow in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (9.4.0)\n",
      "Requirement already satisfied: fastapi in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.95.0)\n",
      "Requirement already satisfied: aiohttp in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (3.8.4)\n",
      "Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (4.4.0)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (1.21.0)\n",
      "Requirement already satisfied: ffmpy in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.3.0)\n",
      "Requirement already satisfied: uvicorn in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.21.1)\n",
      "Requirement already satisfied: websockets>=10.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (10.4)\n",
      "Requirement already satisfied: pydub in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.25.1)\n",
      "Requirement already satisfied: markupsafe in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (2.1.1)\n",
      "Requirement already satisfied: pandas in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (1.5.1)\n",
      "Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (2.2.0)\n",
      "Requirement already satisfied: altair>=4.2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (4.2.2)\n",
      "Requirement already satisfied: aiofiles in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (23.1.0)\n",
      "Requirement already satisfied: mdit-py-plugins<=0.3.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.3.3)\n",
      "Requirement already satisfied: huggingface-hub>=0.13.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (0.13.3)\n",
      "Requirement already satisfied: semantic-version in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (2.10.0)\n",
      "Requirement already satisfied: jinja2 in /home/ubuntu/.local/lib/python3.8/site-packages (from gradio) (3.1.2)\n",
      "Requirement already satisfied: entrypoints in /usr/lib/python3/dist-packages (from altair>=4.2.0->gradio) (0.3)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /usr/lib/python3/dist-packages (from altair>=4.2.0->gradio) (3.2.0)\n",
      "Requirement already satisfied: toolz in /usr/lib/python3/dist-packages (from altair>=4.2.0->gradio) (0.9.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface-hub>=0.13.0->gradio) (4.64.1)\n",
      "Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from huggingface-hub>=0.13.0->gradio) (3.0.12)\n",
      "Requirement already satisfied: packaging>=20.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface-hub>=0.13.0->gradio) (21.3)\n",
      "Requirement already satisfied: mdurl~=0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from markdown-it-py[linkify]>=2.0.0->gradio) (0.1.2)\n",
      "Requirement already satisfied: linkify-it-py<3,>=1 in /home/ubuntu/.local/lib/python3.8/site-packages (from markdown-it-py[linkify]>=2.0.0->gradio) (2.0.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas->gradio) (2023.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas->gradio) (2.8.2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.8.2)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (4.0.2)\n",
      "Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (2.1.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->gradio) (19.3.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (6.0.4)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.3)\n",
      "Requirement already satisfied: starlette<0.27.0,>=0.26.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from fastapi->gradio) (0.26.1)\n",
      "Requirement already satisfied: sniffio in /home/ubuntu/.local/lib/python3.8/site-packages (from httpx->gradio) (1.3.0)\n",
      "Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from httpx->gradio) (1.5.0)\n",
      "Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from httpx->gradio) (0.16.3)\n",
      "Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx->gradio) (2019.11.28)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3/dist-packages (from matplotlib->gradio) (1.0.1)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib->gradio) (2.4.6)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from matplotlib->gradio) (4.38.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /usr/lib/python3/dist-packages (from matplotlib->gradio) (0.10.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->gradio) (2.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests->gradio) (1.26.15)\n",
      "Requirement already satisfied: h11>=0.8 in /home/ubuntu/.local/lib/python3.8/site-packages (from uvicorn->gradio) (0.14.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from uvicorn->gradio) (8.1.3)\n",
      "Requirement already satisfied: anyio<5.0,>=3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from httpcore<0.17.0,>=0.15.0->httpx->gradio) (3.6.2)\n",
      "Requirement already satisfied: uc-micro-py in /home/ubuntu/.local/lib/python3.8/site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify]>=2.0.0->gradio) (1.0.1)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->gradio) (1.14.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Collecting numpy==1.23.5\n",
      "  Using cached numpy-1.23.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: numpy\n",
      "  Attempting uninstall: numpy\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: numpy 1.21.0\n",
      "    Uninstalling numpy-1.21.0:\n",
      "      Successfully uninstalled numpy-1.21.0\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed numpy-1.23.5\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: numba==0.56.4 in /home/ubuntu/.local/lib/python3.8/site-packages (0.56.4)\n",
      "Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /home/ubuntu/.local/lib/python3.8/site-packages (from numba==0.56.4) (0.39.1)\n",
      "Requirement already satisfied: importlib-metadata in /home/ubuntu/.local/lib/python3.8/site-packages (from numba==0.56.4) (5.0.0)\n",
      "Requirement already satisfied: numpy<1.24,>=1.18 in /home/ubuntu/.local/lib/python3.8/site-packages (from numba==0.56.4) (1.23.5)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba==0.56.4) (45.2.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-metadata->numba==0.56.4) (3.15.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: pyworld==0.3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (0.3.0)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/.local/lib/python3.8/site-packages (from pyworld==0.3.0) (1.23.5)\n",
      "Requirement already satisfied: cython>=0.24.0 in /usr/lib/python3/dist-packages (from pyworld==0.3.0) (0.29.14)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting scipy==1.10.1\n",
      "  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)\n",
      "Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from scipy==1.10.1) (1.23.5)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: scipy\n",
      "  Attempting uninstall: scipy\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: scipy 1.9.1\n",
      "    Uninstalling scipy-1.9.1:\n",
      "      Successfully uninstalled scipy-1.9.1\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "scikit-image 0.20.0 requires scipy<1.9.2,>=1.8; python_version <= \"3.9\", but you have scipy 1.10.1 which is incompatible.\n",
      "pandas-profiling 3.4.0 requires scipy<1.10,>=1.4.1, but you have scipy 1.10.1 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed scipy-1.10.1\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: SoundFile==0.12.1 in /home/ubuntu/.local/lib/python3.8/site-packages (0.12.1)\n",
      "Requirement already satisfied: cffi>=1.0 in /usr/lib/python3/dist-packages (from SoundFile==0.12.1) (1.14.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: torch==1.13.1 in /home/ubuntu/.local/lib/python3.8/site-packages (1.13.1+cu116)\n",
      "Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from torch==1.13.1) (4.4.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: torchaudio==0.13.1 in /home/ubuntu/.local/lib/python3.8/site-packages (0.13.1+cu116)\n",
      "Requirement already satisfied: torch==1.13.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from torchaudio==0.13.1) (1.13.1+cu116)\n",
      "Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from torch==1.13.1->torchaudio==0.13.1) (4.4.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: tqdm in /home/ubuntu/.local/lib/python3.8/site-packages (4.64.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: scikit-maad in /home/ubuntu/.local/lib/python3.8/site-packages (1.3.12)\n",
      "Requirement already satisfied: scikit-image>=0.17 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-maad) (0.20.0)\n",
      "Requirement already satisfied: resampy>=0.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-maad) (0.4.2)\n",
      "Requirement already satisfied: pandas>=1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-maad) (1.5.1)\n",
      "Requirement already satisfied: numpy>=1.19 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-maad) (1.23.5)\n",
      "Requirement already satisfied: scipy>=1.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-maad) (1.10.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas>=1.1->scikit-maad) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas>=1.1->scikit-maad) (2023.3)\n",
      "Requirement already satisfied: numba>=0.53 in /home/ubuntu/.local/lib/python3.8/site-packages (from resampy>=0.2->scikit-maad) (0.56.4)\n",
      "Requirement already satisfied: networkx>=2.8 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (3.0)\n",
      "Requirement already satisfied: PyWavelets>=1.1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (1.4.1)\n",
      "Requirement already satisfied: lazy_loader>=0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (0.2)\n",
      "Requirement already satisfied: imageio>=2.4.1 in /usr/lib/python3/dist-packages (from scikit-image>=0.17->scikit-maad) (2.4.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (21.3)\n",
      "Collecting scipy>=1.5\n",
      "  Using cached scipy-1.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.4 MB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tifffile>=2019.7.26 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (2023.3.21)\n",
      "Requirement already satisfied: pillow>=9.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from scikit-image>=0.17->scikit-maad) (9.4.0)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba>=0.53->resampy>=0.2->scikit-maad) (45.2.0)\n",
      "Requirement already satisfied: importlib-metadata in /home/ubuntu/.local/lib/python3.8/site-packages (from numba>=0.53->resampy>=0.2->scikit-maad) (5.0.0)\n",
      "Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /home/ubuntu/.local/lib/python3.8/site-packages (from numba>=0.53->resampy>=0.2->scikit-maad) (0.39.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=20.0->scikit-image>=0.17->scikit-maad) (2.4.6)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1->scikit-maad) (1.14.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-metadata->numba>=0.53->resampy>=0.2->scikit-maad) (3.15.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: scipy\n",
      "  Attempting uninstall: scipy\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: scipy 1.10.1\n",
      "    Uninstalling scipy-1.10.1:\n",
      "      Successfully uninstalled scipy-1.10.1\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mSuccessfully installed scipy-1.9.1\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: praat-parselmouth in /home/ubuntu/.local/lib/python3.8/site-packages (0.4.3)\n",
      "Requirement already satisfied: numpy>=1.7.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from praat-parselmouth) (1.23.5)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: onnx in /home/ubuntu/.local/lib/python3.8/site-packages (1.13.1)\n",
      "Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx) (4.4.0)\n",
      "Requirement already satisfied: numpy>=1.16.6 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx) (1.23.5)\n",
      "Collecting protobuf<4,>=3.20.2\n",
      "  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: protobuf\n",
      "  Attempting uninstall: protobuf\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: protobuf 3.19.6\n",
      "    Uninstalling protobuf-3.19.6:\n",
      "      Successfully uninstalled protobuf-3.19.6\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed protobuf-3.20.3\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: onnxsim in /home/ubuntu/.local/lib/python3.8/site-packages (0.4.19)\n",
      "Requirement already satisfied: onnx in /home/ubuntu/.local/lib/python3.8/site-packages (from onnxsim) (1.13.1)\n",
      "Requirement already satisfied: rich in /home/ubuntu/.local/lib/python3.8/site-packages (from onnxsim) (13.3.3)\n",
      "Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxsim) (4.4.0)\n",
      "Requirement already satisfied: protobuf<4,>=3.20.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxsim) (3.20.3)\n",
      "Requirement already satisfied: numpy>=1.16.6 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxsim) (1.23.5)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from rich->onnxsim) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from rich->onnxsim) (2.13.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->onnxsim) (0.1.2)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: onnxoptimizer in /home/ubuntu/.local/lib/python3.8/site-packages (0.3.10)\n",
      "Requirement already satisfied: onnx in /home/ubuntu/.local/lib/python3.8/site-packages (from onnxoptimizer) (1.13.1)\n",
      "Requirement already satisfied: protobuf<4,>=3.20.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxoptimizer) (3.20.3)\n",
      "Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxoptimizer) (4.4.0)\n",
      "Requirement already satisfied: numpy>=1.16.6 in /home/ubuntu/.local/lib/python3.8/site-packages (from onnx->onnxoptimizer) (1.23.5)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: fairseq==0.12.2 in /home/ubuntu/.local/lib/python3.8/site-packages (0.12.2)\n",
      "Requirement already satisfied: torch in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.13.1+cu116)\n",
      "Requirement already satisfied: hydra-core<1.1,>=1.0.7 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.0.7)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.23.5)\n",
      "Requirement already satisfied: cython in /usr/lib/python3/dist-packages (from fairseq==0.12.2) (0.29.14)\n",
      "Requirement already satisfied: omegaconf<2.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.0.6)\n",
      "Requirement already satisfied: bitarray in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.7.3)\n",
      "Requirement already satisfied: tqdm in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (4.64.1)\n",
      "Requirement already satisfied: sacrebleu>=1.4.12 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.3.1)\n",
      "Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (from fairseq==0.12.2) (1.14.0)\n",
      "Requirement already satisfied: regex in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2023.3.23)\n",
      "Requirement already satisfied: torchaudio>=0.8.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (0.13.1+cu116)\n",
      "Requirement already satisfied: importlib-resources in /home/ubuntu/.local/lib/python3.8/site-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (5.12.0)\n",
      "Requirement already satisfied: antlr4-python3-runtime==4.8 in /home/ubuntu/.local/lib/python3.8/site-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (4.8)\n",
      "Requirement already satisfied: PyYAML>=5.1.* in /usr/lib/python3/dist-packages (from omegaconf<2.1->fairseq==0.12.2) (5.3.1)\n",
      "Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from omegaconf<2.1->fairseq==0.12.2) (4.4.0)\n",
      "Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (4.5.0)\n",
      "Requirement already satisfied: tabulate>=0.8.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.9.0)\n",
      "Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.4.3)\n",
      "Requirement already satisfied: portalocker in /home/ubuntu/.local/lib/python3.8/site-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (2.7.0)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-resources->hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (3.15.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: librosa==0.8.1 in /home/ubuntu/.local/lib/python3.8/site-packages (0.8.1)\n",
      "Requirement already satisfied: joblib>=0.14 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (1.2.0)\n",
      "Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/lib/python3/dist-packages (from librosa==0.8.1) (0.22.2.post1)\n",
      "Requirement already satisfied: scipy>=1.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (1.9.1)\n",
      "Requirement already satisfied: soundfile>=0.10.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (0.12.1)\n",
      "Requirement already satisfied: numba>=0.43.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (0.56.4)\n",
      "Requirement already satisfied: pooch>=1.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (1.7.0)\n",
      "Requirement already satisfied: decorator>=3.0.0 in /usr/lib/python3/dist-packages (from librosa==0.8.1) (4.4.2)\n",
      "Requirement already satisfied: resampy>=0.2.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (0.4.2)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (21.3)\n",
      "Requirement already satisfied: numpy>=1.15.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (1.23.5)\n",
      "Requirement already satisfied: audioread>=2.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from librosa==0.8.1) (3.0.0)\n",
      "Requirement already satisfied: importlib-metadata in /home/ubuntu/.local/lib/python3.8/site-packages (from numba>=0.43.0->librosa==0.8.1) (5.0.0)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba>=0.43.0->librosa==0.8.1) (45.2.0)\n",
      "Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /home/ubuntu/.local/lib/python3.8/site-packages (from numba>=0.43.0->librosa==0.8.1) (0.39.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=20.0->librosa==0.8.1) (2.4.6)\n",
      "Requirement already satisfied: platformdirs>=2.5.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from pooch>=1.0->librosa==0.8.1) (3.2.0)\n",
      "Requirement already satisfied: requests>=2.19.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from pooch>=1.0->librosa==0.8.1) (2.28.1)\n",
      "Requirement already satisfied: cffi>=1.0 in /usr/lib/python3/dist-packages (from soundfile>=0.10.2->librosa==0.8.1) (1.14.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (2.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (2019.11.28)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (2.1.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (1.26.15)\n",
      "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-metadata->numba>=0.43.0->librosa==0.8.1) (3.15.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: tensorboard in /home/ubuntu/.local/lib/python3.8/site-packages (2.11.2)\n",
      "Requirement already satisfied: grpcio>=1.24.3 in /usr/lib/python3/dist-packages (from tensorboard) (1.29.1)\n",
      "Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard) (0.34.2)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (2.28.1)\n",
      "Requirement already satisfied: setuptools>=41.0.0 in /usr/lib/python3/dist-packages (from tensorboard) (45.2.0)\n",
      "Requirement already satisfied: numpy>=1.12.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (1.23.5)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (1.8.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (2.17.0)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/lib/python3/dist-packages (from tensorboard) (0.4.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (0.6.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (2.2.3)\n",
      "Requirement already satisfied: protobuf<4,>=3.9.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (3.20.3)\n",
      "Requirement already satisfied: absl-py>=0.4 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard) (1.4.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3/dist-packages (from tensorboard) (3.1.1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard) (1.14.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard) (4.0.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard) (4.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard) (0.2.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard) (1.26.15)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard) (2.8)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard) (2.1.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard) (2019.11.28)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: PyQt5 in /home/ubuntu/.local/lib/python3.8/site-packages (5.15.9)\n",
      "Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from PyQt5) (5.15.2)\n",
      "Requirement already satisfied: PyQt5-sip<13,>=12.11 in /home/ubuntu/.local/lib/python3.8/site-packages (from PyQt5) (12.11.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: huggingface_hub in /home/ubuntu/.local/lib/python3.8/site-packages (0.13.3)\n",
      "Requirement already satisfied: packaging>=20.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (21.3)\n",
      "Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from huggingface_hub) (3.0.12)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (4.4.0)\n",
      "Requirement already satisfied: requests in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (2.28.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub) (5.3.1)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (4.64.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=20.9->huggingface_hub) (2.4.6)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests->huggingface_hub) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface_hub) (2.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface_hub) (2019.11.28)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests->huggingface_hub) (1.26.15)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116\n",
      "Requirement already satisfied: datasets in /home/ubuntu/.local/lib/python3.8/site-packages (2.11.0)\n",
      "Requirement already satisfied: pandas in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (1.5.1)\n",
      "Requirement already satisfied: pyarrow>=8.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (11.0.0)\n",
      "Requirement already satisfied: dill<0.3.7,>=0.3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (0.3.6)\n",
      "Requirement already satisfied: aiohttp in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (3.8.4)\n",
      "Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (0.13.3)\n",
      "Requirement already satisfied: requests>=2.19.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (2.28.1)\n",
      "Requirement already satisfied: responses<0.19 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (0.18.0)\n",
      "Requirement already satisfied: multiprocess in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (0.70.14)\n",
      "Requirement already satisfied: xxhash in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (3.2.0)\n",
      "Requirement already satisfied: packaging in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (21.3)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (4.64.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (1.23.5)\n",
      "Requirement already satisfied: fsspec[http]>=2021.11.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from datasets) (2023.3.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from datasets) (5.3.1)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.3)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (1.8.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->datasets) (19.3.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (6.0.4)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.1)\n",
      "Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (2.1.1)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/ubuntu/.local/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.2)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.4.0)\n",
      "Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.0.12)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->datasets) (2.4.6)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->datasets) (2019.11.28)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->datasets) (2.8)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from pandas->datasets) (2023.3)\n",
      "Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.14.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: praat-parselmouth in /home/ubuntu/.local/lib/python3.8/site-packages (0.4.3)\n",
      "Requirement already satisfied: numpy>=1.7.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from praat-parselmouth) (1.23.5)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: ipywidgets in /home/ubuntu/.local/lib/python3.8/site-packages (8.0.2)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /usr/lib/python3/dist-packages (from ipywidgets) (5.2.0)\n",
      "Requirement already satisfied: ipython>=6.1.0 in /usr/lib/python3/dist-packages (from ipywidgets) (7.13.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from ipywidgets) (5.5.0)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from ipywidgets) (4.0.3)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from ipywidgets) (3.0.3)\n",
      "Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from ipython>=6.1.0->ipywidgets) (4.6.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: huggingface_hub in /home/ubuntu/.local/lib/python3.8/site-packages (0.13.3)\n",
      "Requirement already satisfied: packaging>=20.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (21.3)\n",
      "Requirement already satisfied: requests in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (2.28.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub) (5.3.1)\n",
      "Requirement already satisfied: filelock in /usr/lib/python3/dist-packages (from huggingface_hub) (3.0.12)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (4.64.1)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from huggingface_hub) (4.4.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=20.9->huggingface_hub) (2.4.6)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests->huggingface_hub) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface_hub) (2.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests->huggingface_hub) (1.26.15)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface_hub) (2019.11.28)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pip==23.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (23.0.1)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: fairseq==0.12.2 in /home/ubuntu/.local/lib/python3.8/site-packages (0.12.2)\n",
      "Requirement already satisfied: torchaudio>=0.8.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (0.13.1+cu116)\n",
      "Requirement already satisfied: regex in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2023.3.23)\n",
      "Requirement already satisfied: cython in /usr/lib/python3/dist-packages (from fairseq==0.12.2) (0.29.14)\n",
      "Requirement already satisfied: bitarray in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.7.3)\n",
      "Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (from fairseq==0.12.2) (1.14.0)\n",
      "Requirement already satisfied: torch in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.13.1+cu116)\n",
      "Requirement already satisfied: numpy in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.23.5)\n",
      "Requirement already satisfied: sacrebleu>=1.4.12 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.3.1)\n",
      "Requirement already satisfied: tqdm in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (4.64.1)\n",
      "Requirement already satisfied: omegaconf<2.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (2.0.6)\n",
      "Requirement already satisfied: hydra-core<1.1,>=1.0.7 in /home/ubuntu/.local/lib/python3.8/site-packages (from fairseq==0.12.2) (1.0.7)\n",
      "Requirement already satisfied: importlib-resources in /home/ubuntu/.local/lib/python3.8/site-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (5.12.0)\n",
      "Requirement already satisfied: antlr4-python3-runtime==4.8 in /home/ubuntu/.local/lib/python3.8/site-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (4.8)\n",
      "Requirement already satisfied: PyYAML>=5.1.* in /usr/lib/python3/dist-packages (from omegaconf<2.1->fairseq==0.12.2) (5.3.1)\n",
      "Requirement already satisfied: typing-extensions in /home/ubuntu/.local/lib/python3.8/site-packages (from omegaconf<2.1->fairseq==0.12.2) (4.4.0)\n",
      "Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (4.5.0)\n",
      "Requirement already satisfied: tabulate>=0.8.9 in /home/ubuntu/.local/lib/python3.8/site-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.9.0)\n",
      "Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.4.3)\n",
      "Requirement already satisfied: portalocker in /home/ubuntu/.local/lib/python3.8/site-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (2.7.0)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: zipp>=3.1.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from importlib-resources->hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (3.15.0)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mEnabling notebook extension jupyter-js-widgets/extension...\n",
      "      - Validating: \u001b[32mOK\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting numpy==1.21\n",
      "  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: numpy\n",
      "  Attempting uninstall: numpy\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: numpy 1.23.5\n",
      "    Uninstalling numpy-1.23.5:\n",
      "      Successfully uninstalled numpy-1.23.5\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.\n",
      "scikit-image 0.20.0 requires numpy>=1.21.1, but you have numpy 1.21.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed numpy-1.21.0\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: Invalid requirement: 'protobuf=3.9.2'\n",
      "Hint: = is not a valid operator. Did you mean == ?\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mFound existing installation: tensorflow 2.11.0\n",
      "Uninstalling tensorflow-2.11.0:\n",
      "  Successfully uninstalled tensorflow-2.11.0\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting tensorflow==2.11.0\n",
      "  Using cached tensorflow-2.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)\n",
      "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (1.14.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (1.6.2)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (1.29.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (3.3.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (1.1.0)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (0.32.0)\n",
      "Requirement already satisfied: packaging in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (21.3)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (0.2.0)\n",
      "Requirement already satisfied: keras<2.12,>=2.11.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (2.11.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (0.4.0)\n",
      "Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (45.2.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (1.4.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (2.10.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /usr/lib/python3/dist-packages (from tensorflow==2.11.0) (1.11.2)\n",
      "Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (2.11.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (16.0.0)\n",
      "Requirement already satisfied: tensorboard<2.12,>=2.11 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (2.11.2)\n",
      "Requirement already satisfied: numpy>=1.20 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (1.21.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (4.4.0)\n",
      "Collecting protobuf<3.20,>=3.9.2\n",
      "  Using cached protobuf-3.19.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)\n",
      "Requirement already satisfied: flatbuffers>=2.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorflow==2.11.0) (23.3.3)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (1.8.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/lib/python3/dist-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (0.4.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (0.6.1)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.28.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.17.0)\n",
      "Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (0.34.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.2.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /usr/lib/python3/dist-packages (from tensorboard<2.12,>=2.11->tensorflow==2.11.0) (3.1.1)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->tensorflow==2.11.0) (2.4.6)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (4.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (0.2.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (4.0.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2019.11.28)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (1.26.15)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.8)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /home/ubuntu/.local/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.1.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow==2.11.0) (2.1.1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0mInstalling collected packages: protobuf, tensorflow\n",
      "  Attempting uninstall: protobuf\n",
      "\u001b[33m    WARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m    Found existing installation: protobuf 3.20.3\n",
      "    Uninstalling protobuf-3.20.3:\n",
      "      Successfully uninstalled protobuf-3.20.3\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed protobuf-3.19.6 tensorflow-2.11.0\n",
      "\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Ignoring invalid distribution -cipy (/home/ubuntu/.local/lib/python3.8/site-packages)\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!cat requirements.txt | xargs -n 1 pip install --extra-index-url https://download.pytorch.org/whl/cu116\n",
    "!pip install praat-parselmouth\n",
    "!pip install ipywidgets\n",
    "!pip install huggingface_hub\n",
    "!pip install pip==23.0.1 # fix pip version for fairseq install\n",
    "!pip install fairseq==0.12.2\n",
    "!jupyter nbextension enable --py widgetsnbextension\n",
    "!pip install numpy==1.21\n",
    "!pip install --upgrade protobuf=3.9.2\n",
    "!pip uninstall -y tensorflow\n",
    "!pip install tensorflow==2.11.0 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "51750fba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished!\n"
     ]
    }
   ],
   "source": [
    "import tarfile\n",
    "import os\n",
    "from zipfile import ZipFile\n",
    "# taken from https://github.com/CookiePPP/cookietts/blob/master/CookieTTS/utils/dataset/extract_unknown.py\n",
    "def extract(path):\n",
    "    if path.endswith(\".zip\"):\n",
    "        with ZipFile(path, 'r') as zipObj:\n",
    "           zipObj.extractall(os.path.split(path)[0])\n",
    "    elif path.endswith(\".tar.bz2\"):\n",
    "        tar = tarfile.open(path, \"r:bz2\")\n",
    "        tar.extractall(os.path.split(path)[0])\n",
    "        tar.close()\n",
    "    elif path.endswith(\".tar.gz\"):\n",
    "        tar = tarfile.open(path, \"r:gz\")\n",
    "        tar.extractall(os.path.split(path)[0])\n",
    "        tar.close()\n",
    "    elif path.endswith(\".tar\"):\n",
    "        tar = tarfile.open(path, \"r:\")\n",
    "        tar.extractall(os.path.split(path)[0])\n",
    "        tar.close()\n",
    "    elif path.endswith(\".7z\"):\n",
    "        import py7zr\n",
    "        archive = py7zr.SevenZipFile(path, mode='r')\n",
    "        archive.extractall(path=os.path.split(path)[0])\n",
    "        archive.close()\n",
    "    else:\n",
    "        raise NotImplementedError(f\"{path} extension not implemented.\")\n",
    "\n",
    "# taken from https://github.com/CookiePPP/cookietts/tree/master/CookieTTS/_0_download/scripts\n",
    "\n",
    "# megatools download urls\n",
    "win64_url = \"https://megatools.megous.com/builds/builds/megatools-1.11.1.20230212-win64.zip\"\n",
    "win32_url = \"https://megatools.megous.com/builds/builds/megatools-1.11.1.20230212-win32.zip\"\n",
    "linux_url = \"https://megatools.megous.com/builds/builds/megatools-1.11.1.20230212-linux-x86_64.tar.gz\"\n",
    "# download megatools\n",
    "from sys import platform\n",
    "import os\n",
    "import urllib.request\n",
    "import subprocess\n",
    "from time import sleep\n",
    "\n",
    "if platform == \"linux\" or platform == \"linux2\":\n",
    "        dl_url = linux_url\n",
    "elif platform == \"darwin\":\n",
    "    raise NotImplementedError('MacOS not supported.')\n",
    "elif platform == \"win32\":\n",
    "        dl_url = win64_url\n",
    "else:\n",
    "    raise NotImplementedError ('Unknown Operating System.')\n",
    "\n",
    "dlname = dl_url.split(\"/\")[-1]\n",
    "if dlname.endswith(\".zip\"):\n",
    "    binary_folder = dlname[:-4] # remove .zip\n",
    "elif dlname.endswith(\".tar.gz\"):\n",
    "    binary_folder = dlname[:-7] # remove .tar.gz\n",
    "else:\n",
    "    raise NameError('downloaded megatools has unknown archive file extension!')\n",
    "\n",
    "if not os.path.exists(binary_folder):\n",
    "    print('\"megatools\" not found. Downloading...')\n",
    "    if not os.path.exists(dlname):\n",
    "        urllib.request.urlretrieve(dl_url, dlname)\n",
    "    assert os.path.exists(dlname), 'failed to download.'\n",
    "    extract(dlname)\n",
    "    sleep(0.10)\n",
    "    os.unlink(dlname)\n",
    "    print(\"Done!\")\n",
    "\n",
    "\n",
    "binary_folder = os.path.abspath(binary_folder)\n",
    "\n",
    "def megadown(download_link, filename='.', verbose=False):\n",
    "    \"\"\"Use megatools binary executable to download files and folders from MEGA.nz .\"\"\"\n",
    "    filename = ' --path \"'+os.path.abspath(filename)+'\"' if filename else \"\"\n",
    "    wd_old = os.getcwd()\n",
    "    os.chdir(binary_folder)\n",
    "    try:\n",
    "        if platform == \"linux\" or platform == \"linux2\":\n",
    "            subprocess.call(f'./megatools dl{filename}{\" --debug http\" if verbose else \"\"} {download_link}', shell=True)\n",
    "        elif platform == \"win32\":\n",
    "            subprocess.call(f'megatools.exe dl{filename}{\" --debug http\" if verbose else \"\"} {download_link}', shell=True)\n",
    "    except:\n",
    "        os.chdir(wd_old) # don't let user stop download without going back to correct directory first\n",
    "        raise\n",
    "    os.chdir(wd_old)\n",
    "    return filename\n",
    "\n",
    "import urllib.request\n",
    "from tqdm import tqdm\n",
    "import gdown\n",
    "from os.path import exists\n",
    "\n",
    "def request_url_with_progress_bar(url, filename):\n",
    "    class DownloadProgressBar(tqdm):\n",
    "        def update_to(self, b=1, bsize=1, tsize=None):\n",
    "            if tsize is not None:\n",
    "                self.total = tsize\n",
    "            self.update(b * bsize - self.n)\n",
    "    \n",
    "    def download_url(url, filename):\n",
    "        with DownloadProgressBar(unit='B', unit_scale=True,\n",
    "                                 miniters=1, desc=url.split('/')[-1]) as t:\n",
    "            filename, headers = urllib.request.urlretrieve(url, filename=filename, reporthook=t.update_to)\n",
    "            print(\"Downloaded to \"+filename)\n",
    "    download_url(url, filename)\n",
    "\n",
    "\n",
    "def download(urls, dataset='', filenames=None, force_dl=False, username='', password='', auth_needed=False):\n",
    "    assert filenames is None or len(urls) == len(filenames), f\"number of urls does not match filenames. Expected {len(filenames)} urls, containing the files listed below.\\n{filenames}\"\n",
    "    assert not auth_needed or (len(username) and len(password)), f\"username and password needed for {dataset} Dataset\"\n",
    "    if filenames is None:\n",
    "        filenames = [None,]*len(urls)\n",
    "    for i, (url, filename) in enumerate(zip(urls, filenames)):\n",
    "        print(f\"Downloading File from {url}\")\n",
    "        #if filename is None:\n",
    "        #    filename = url.split(\"/\")[-1]\n",
    "        if filename and (not force_dl) and exists(filename):\n",
    "            print(f\"{filename} Already Exists, Skipping.\")\n",
    "            continue\n",
    "        if 'drive.google.com' in url:\n",
    "            assert 'https://drive.google.com/uc?id=' in url, 'Google Drive links should follow the format \"https://drive.google.com/uc?id=1eQAnaoDBGQZldPVk-nzgYzRbcPSmnpv6\".\\nWhere id=XXXXXXXXXXXXXXXXX is the Google Drive Share ID.'\n",
    "            gdown.download(url, filename, quiet=False)\n",
    "        elif 'mega.nz' in url:\n",
    "            megadown(url, filename)\n",
    "        else:\n",
    "            #urllib.request.urlretrieve(url, filename=filename) # no progress bar\n",
    "            request_url_with_progress_bar(url, filename) # with progress bar\n",
    "\n",
    "import huggingface_hub\n",
    "import os\n",
    "import shutil\n",
    "\n",
    "class HFModels:\n",
    "    def __init__(self, repo = \"therealvul/so-vits-svc-4.0\", \n",
    "            model_dir = \"hf_vul_models\"):\n",
    "        self.model_repo = huggingface_hub.Repository(local_dir=model_dir,\n",
    "            clone_from=repo, skip_lfs_files=True)\n",
    "        self.repo = repo\n",
    "        self.model_dir = model_dir\n",
    "\n",
    "        self.model_folders = os.listdir(model_dir)\n",
    "        self.model_folders.remove('.git')\n",
    "        self.model_folders.remove('.gitattributes')\n",
    "\n",
    "    def list_models(self):\n",
    "        return self.model_folders\n",
    "\n",
    "    # Downloads model;\n",
    "    # copies config to target_dir and moves model to target_dir\n",
    "    def download_model(self, model_name, target_dir):\n",
    "        if not model_name in self.model_folders:\n",
    "            raise Exception(model_name + \" not found\")\n",
    "        model_dir = self.model_dir\n",
    "        charpath = os.path.join(model_dir,model_name)\n",
    "\n",
    "        gen_pt = next(x for x in os.listdir(charpath) if x.startswith(\"G_\"))\n",
    "        cfg = next(x for x in os.listdir(charpath) if x.endswith(\"json\"))\n",
    "        try:\n",
    "          clust = next(x for x in os.listdir(charpath) if x.endswith(\"pt\"))\n",
    "        except StopIteration as e:\n",
    "          print(\"Note - no cluster model for \"+model_name)\n",
    "          clust = None\n",
    "\n",
    "        if not os.path.exists(target_dir):\n",
    "            os.makedirs(target_dir, exist_ok=True)\n",
    "\n",
    "        gen_dir = huggingface_hub.hf_hub_download(repo_id = self.repo,\n",
    "            filename = model_name + \"/\" + gen_pt) # this is a symlink\n",
    "        \n",
    "        if clust is not None:\n",
    "          clust_dir = huggingface_hub.hf_hub_download(repo_id = self.repo,\n",
    "              filename = model_name + \"/\" + clust) # this is a symlink\n",
    "          shutil.move(os.path.realpath(clust_dir), os.path.join(target_dir, clust))\n",
    "          clust_out = os.path.join(target_dir, clust)\n",
    "        else:\n",
    "          clust_out = None\n",
    "\n",
    "        shutil.copy(os.path.join(charpath,cfg),os.path.join(target_dir, cfg))\n",
    "        shutil.move(os.path.realpath(gen_dir), os.path.join(target_dir, gen_pt))\n",
    "\n",
    "        return {\"config_path\": os.path.join(target_dir,cfg),\n",
    "            \"generator_path\": os.path.join(target_dir,gen_pt),\n",
    "            \"cluster_path\": clust_out}\n",
    "\n",
    "# Example usage\n",
    "# vul_models = HFModels()\n",
    "# print(vul_models.list_models())\n",
    "# print(\"Applejack (singing)\" in vul_models.list_models())\n",
    "# vul_models.download_model(\"Applejack (singing)\",\"models/Applejack (singing)\")\n",
    "\n",
    "    print(\"Finished!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "90cbf641",
   "metadata": {},
   "outputs": [],
   "source": [
    "#@title Open the file explorer on the left of your screen and drag-and-drop an audio file anywhere. Then run the below cell.\n",
    "import os\n",
    "import glob\n",
    "import json\n",
    "import copy\n",
    "import logging\n",
    "import io\n",
    "from ipywidgets import widgets\n",
    "from pathlib import Path\n",
    "from IPython.display import Audio, display\n",
    "\n",
    "os.chdir('/home/ubuntu/so-vits-svc')\n",
    "\n",
    "import torch\n",
    "from inference import infer_tool\n",
    "from inference import slicer\n",
    "from inference.infer_tool import Svc\n",
    "import soundfile\n",
    "import numpy as np\n",
    "\n",
    "MODELS_DIR = \"models\"\n",
    "\n",
    "def get_speakers():\n",
    "  speakers = []\n",
    "  for _,dirs,_ in os.walk(MODELS_DIR):\n",
    "    for folder in dirs:\n",
    "      cur_speaker = {}\n",
    "      # Look for G_****.pth\n",
    "      g = glob.glob(os.path.join(MODELS_DIR,folder,'G_*.pth'))\n",
    "      if not len(g):\n",
    "        print(\"Skipping \"+folder+\", no G_*.pth\")\n",
    "        continue\n",
    "      cur_speaker[\"model_path\"] = g[0]\n",
    "      cur_speaker[\"model_folder\"] = folder\n",
    "\n",
    "      # Look for *.pt (clustering model)\n",
    "      clst = glob.glob(os.path.join(MODELS_DIR,folder,'*.pt'))\n",
    "      if not len(clst):\n",
    "        print(\"Note: No clustering model found for \"+folder)\n",
    "        cur_speaker[\"cluster_path\"] = \"\"\n",
    "      else:\n",
    "        cur_speaker[\"cluster_path\"] = clst[0]\n",
    "\n",
    "      # Look for config.json\n",
    "      cfg = glob.glob(os.path.join(MODELS_DIR,folder,'*.json'))\n",
    "      if not len(cfg):\n",
    "        print(\"Skipping \"+folder+\", no config json\")\n",
    "        continue\n",
    "      cur_speaker[\"cfg_path\"] = cfg[0]\n",
    "      with open(cur_speaker[\"cfg_path\"]) as f:\n",
    "        try:\n",
    "          cfg_json = json.loads(f.read())\n",
    "        except Exception as e:\n",
    "          print(\"Malformed config json in \"+folder)\n",
    "        for name, i in cfg_json[\"spk\"].items():\n",
    "          cur_speaker[\"name\"] = name\n",
    "          cur_speaker[\"id\"] = i\n",
    "          if not name.startswith('.'):\n",
    "            speakers.append(copy.copy(cur_speaker))\n",
    "\n",
    "    return sorted(speakers, key=lambda x:x[\"name\"].lower())\n",
    "\n",
    "logging.getLogger('numba').setLevel(logging.WARNING)\n",
    "chunks_dict = infer_tool.read_temp(\"inference/chunks_temp.json\")\n",
    "existing_files = []\n",
    "slice_db = -40\n",
    "wav_format = 'wav'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "20d173aa",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: No clustering model found for ye200k\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "be59d609463d48a9a79eef188108a6fd",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Dropdown(options=('aimodel', 'kendrick01'), value='aimodel')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "779d7051e6d744cd8e0fabf307400a88",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "IntText(value=12, description='Transpose')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f5c96dfc95704f07881e62f086a44548",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "FloatText(value=0.0, description='Clustering Ratio')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "932f86e157d4482a8dbf17fd66828b1e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "FloatText(value=0.4, description='Noise Scale')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bb759b2555494d87a0bd424e8986139f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Checkbox(value=False, description='Auto pitch f0 (do not use for singing)')"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "141d3576d09d4662af45860bb4e20eea",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Button(description='Convert', style=ButtonStyle())"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3bba35a4a7c14d9daf5c905629447387",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Button(description='Delete all audio files', style=ButtonStyle())"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ubuntu/so-vits-svc/models/ye200k/G_199200.pth\n",
      "True\n",
      "load model(s) from hubert/checkpoint_best_legacy_500.pt\n",
      "INFO:fairseq.tasks.text_to_speech:Please install tensorboardX: pip install tensorboardX\n"
     ]
    }
   ],
   "source": [
    "class InferenceGui():\n",
    "  def __init__(self):\n",
    "    self.speakers = get_speakers()\n",
    "    self.speaker_list = [x[\"name\"] for x in self.speakers]\n",
    "    self.speaker_box = widgets.Dropdown(\n",
    "        options = self.speaker_list\n",
    "    )\n",
    "    display(self.speaker_box)\n",
    "\n",
    "    def convert_cb(btn):\n",
    "      self.convert()\n",
    "    def clean_cb(btn):\n",
    "      self.clean()\n",
    "\n",
    "    self.convert_btn = widgets.Button(description=\"Convert\")\n",
    "    self.convert_btn.on_click(convert_cb)\n",
    "    self.clean_btn = widgets.Button(description=\"Delete all audio files\")\n",
    "    self.clean_btn.on_click(clean_cb)\n",
    "\n",
    "    self.trans_tx = widgets.IntText(value=12, description='Transpose')\n",
    "    self.cluster_ratio_tx = widgets.FloatText(value=0.0, \n",
    "      description='Clustering Ratio')\n",
    "    self.noise_scale_tx = widgets.FloatText(value=0.4, \n",
    "      description='Noise Scale')\n",
    "    self.auto_pitch_ck = widgets.Checkbox(value=False, description=\n",
    "      'Auto pitch f0 (do not use for singing)')\n",
    "\n",
    "    display(self.trans_tx)\n",
    "    display(self.cluster_ratio_tx)\n",
    "    display(self.noise_scale_tx)\n",
    "    display(self.auto_pitch_ck)\n",
    "    display(self.convert_btn)\n",
    "    display(self.clean_btn)\n",
    "\n",
    "  def convert(self):\n",
    "    trans = int(self.trans_tx.value)\n",
    "    speaker = next(x for x in self.speakers if x[\"name\"] == \n",
    "          self.speaker_box.value)\n",
    "    spkpth2 = os.path.join(os.getcwd(),speaker[\"model_path\"])\n",
    "    print(spkpth2)\n",
    "    print(os.path.exists(spkpth2))\n",
    "\n",
    "    svc_model = Svc(speaker[\"model_path\"], speaker[\"cfg_path\"], \n",
    "      cluster_model_path=speaker[\"cluster_path\"])\n",
    "    \n",
    "    input_filepaths = [f for f in glob.glob('/home/ubuntu/**/*.*', recursive=True)\n",
    "     if f not in existing_files and \n",
    "     any(f.endswith(ex) for ex in ['.wav','.flac','.mp3','.ogg','.opus'])]\n",
    "    input_filepaths = [f for f in input_filepaths if \"Vocals.\" in f]\n",
    "    for name in input_filepaths:\n",
    "      print(\"Converting \"+os.path.split(name)[-1])\n",
    "      infer_tool.format_wav(name)\n",
    "\n",
    "      wav_path = str(Path(name).with_suffix('.wav'))\n",
    "      wav_name = Path(name).stem\n",
    "      chunks = slicer.cut(wav_path, db_thresh=slice_db)\n",
    "      audio_data, audio_sr = slicer.chunks2audio(wav_path, chunks)\n",
    "\n",
    "      audio = []\n",
    "      for (slice_tag, data) in audio_data:\n",
    "          print(f'#=====segment start, '\n",
    "              f'{round(len(data)/audio_sr, 3)}s======')\n",
    "          \n",
    "          length = int(np.ceil(len(data) / audio_sr *\n",
    "              svc_model.target_sample))\n",
    "          \n",
    "          if slice_tag:\n",
    "              print('jump empty segment')\n",
    "              _audio = np.zeros(length)\n",
    "          else:\n",
    "              # Padding \"fix\" for noise\n",
    "              pad_len = int(audio_sr * 0.5)\n",
    "              data = np.concatenate([np.zeros([pad_len]),\n",
    "                  data, np.zeros([pad_len])])\n",
    "              raw_path = io.BytesIO()\n",
    "              soundfile.write(raw_path, data, audio_sr, format=\"wav\")\n",
    "              raw_path.seek(0)\n",
    "              _cluster_ratio = 0.0\n",
    "              if speaker[\"cluster_path\"] != \"\":\n",
    "                _cluster_ratio = float(self.cluster_ratio_tx.value)\n",
    "              out_audio, out_sr = svc_model.infer(\n",
    "                  speaker[\"name\"], trans, raw_path,\n",
    "                  cluster_infer_ratio = _cluster_ratio,\n",
    "                  auto_predict_f0 = bool(self.auto_pitch_ck.value),\n",
    "                  noice_scale = float(self.noise_scale_tx.value))\n",
    "              _audio = out_audio.cpu().numpy()\n",
    "              pad_len = int(svc_model.target_sample * 0.5)\n",
    "              _audio = _audio[pad_len:-pad_len]\n",
    "          audio.extend(list(infer_tool.pad_array(_audio, length)))\n",
    "          \n",
    "      res_path = os.path.join('/home/ubuntu/',\n",
    "          f'{wav_name}_{trans}_key_'\n",
    "          f'{speaker[\"name\"]}.{wav_format}')\n",
    "      soundfile.write(res_path, audio, svc_model.target_sample,\n",
    "          format=wav_format)\n",
    "      display(Audio(res_path, autoplay=True)) # display audio file\n",
    "    pass\n",
    "\n",
    "  def clean(self):\n",
    "     input_filepaths = [f for f in glob.glob('/home/ubuntu/**/*.*', recursive=True)\n",
    "     if f not in existing_files and \n",
    "     any(f.endswith(ex) for ex in ['.wav','.flac','.mp3','.ogg','.opus'])]\n",
    "     for f in input_filepaths:\n",
    "       os.remove(f)\n",
    "\n",
    "inference_gui = InferenceGui()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4ecedad9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ubuntu\n"
     ]
    }
   ],
   "source": [
    "%cd .."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "54490211",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'backdown_Vocals_0_key_aimodel.wav'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-12-acda87926201>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpydub\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAudioSegment\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0msound1\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mAudioSegment\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_file\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"backdown_Vocals_0_key_aimodel.wav\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mformat\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"wav\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0msound2\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mAudioSegment\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_file\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"backdown_Instruments.wav\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mformat\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"wav\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;31m# sound1 6 dB louder\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pydub/audio_segment.py\u001b[0m in \u001b[0;36mfrom_file\u001b[0;34m(cls, file, format, codec, parameters, start_second, duration, **kwargs)\u001b[0m\n\u001b[1;32m    649\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    650\u001b[0m             \u001b[0mfilename\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 651\u001b[0;31m         \u001b[0mfile\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mclose_file\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_fd_or_path_or_tempfile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'rb'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtempfile\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    652\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    653\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mformat\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pydub/utils.py\u001b[0m in \u001b[0;36m_fd_or_path_or_tempfile\u001b[0;34m(fd, mode, tempfile)\u001b[0m\n\u001b[1;32m     58\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     59\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbasestring\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 60\u001b[0;31m         \u001b[0mfd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfd\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmode\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmode\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     61\u001b[0m         \u001b[0mclose_fd\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'backdown_Vocals_0_key_aimodel.wav'"
     ]
    }
   ],
   "source": [
    "from pydub import AudioSegment\n",
    "sound1 = AudioSegment.from_file(\"backdown_Vocals_0_key_aimodel.wav\", format=\"wav\")\n",
    "sound2 = AudioSegment.from_file(\"backdown_Instruments.wav\", format=\"wav\")\n",
    "\n",
    "# sound1 6 dB louder\n",
    "louder = sound1 + 6\n",
    "\n",
    "# Overlay sound2 over sound1 at position 0  (use louder instead of sound1 to use the louder version)\n",
    "overlay = sound1.overlay(sound2, position=0)\n",
    "\n",
    "\n",
    "# simple export\n",
    "file_handle = overlay.export(\"output.mp3\", format=\"mp3\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "98cb4c39",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "517f2761",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea202df5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
